<?php

namespace App\Services;

use App\Models\Accounting\FiscalPeriod;
use App\Models\Accounting\Journal;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use RuntimeException;

/**
 * Creates double-entry journals. Every posting in the system funnels through
 * `post()`, which refuses unbalanced entries and entries dated inside a closed
 * fiscal period.
 */
class JournalService
{
    public function __construct(private readonly DocumentNumberService $numbers) {}

    /**
     * @param  array<int,array{account_id:int,debit?:float,credit?:float,description?:string|null,partner_id?:int|null}>  $lines
     */
    public function post(
        array $lines,
        string $date,
        string $type = 'general',
        ?string $description = null,
        ?Model $source = null,
        ?string $reference = null,
        string $status = 'posted',
    ): Journal {
        $this->guardPeriod($date);

        // Drop no-op legs so callers can build lines unconditionally.
        $lines = array_values(array_filter($lines, fn ($l) => round((float) ($l['debit'] ?? 0), 2) !== 0.0
            || round((float) ($l['credit'] ?? 0), 2) !== 0.0));

        if (count($lines) < 2) {
            throw new RuntimeException('Jurnal membutuhkan minimal dua baris dengan nilai.');
        }

        $totalDebit = round(array_sum(array_map(fn ($l) => (float) ($l['debit'] ?? 0), $lines)), 2);
        $totalCredit = round(array_sum(array_map(fn ($l) => (float) ($l['credit'] ?? 0), $lines)), 2);

        if (abs($totalDebit - $totalCredit) > 0.009) {
            throw new RuntimeException(sprintf(
                'Jurnal tidak seimbang: debit %s vs kredit %s.',
                number_format($totalDebit, 2, ',', '.'),
                number_format($totalCredit, 2, ',', '.')
            ));
        }

        return DB::transaction(function () use ($lines, $date, $type, $description, $source, $reference, $status, $totalDebit, $totalCredit) {
            $journal = Journal::create([
                'journal_no' => $this->numbers->next('journal', $date),
                'date' => $date,
                'type' => $type,
                'reference' => $reference,
                'description' => $description,
                'source_type' => $source ? $source::class : null,
                'source_id' => $source?->getKey(),
                'total_debit' => $totalDebit,
                'total_credit' => $totalCredit,
                'status' => $status,
                'created_by' => Auth::id(),
            ]);

            foreach ($lines as $line) {
                $journal->lines()->create([
                    'account_id' => $line['account_id'],
                    'partner_id' => $line['partner_id'] ?? null,
                    'description' => $line['description'] ?? $description,
                    'debit' => round((float) ($line['debit'] ?? 0), 2),
                    'credit' => round((float) ($line['credit'] ?? 0), 2),
                ]);
            }

            return $journal;
        });
    }

    /** Writes the mirror image of a journal and links the two together. */
    public function reverse(Journal $journal, ?string $date = null, ?string $description = null): Journal
    {
        if ($journal->status === 'reversed') {
            throw new RuntimeException("Jurnal {$journal->journal_no} sudah dibalik.");
        }

        $lines = $journal->lines->map(fn ($line) => [
            'account_id' => $line->account_id,
            'partner_id' => $line->partner_id,
            'description' => $line->description,
            'debit' => (float) $line->credit,
            'credit' => (float) $line->debit,
        ])->all();

        $reversal = $this->post(
            $lines,
            $date ?? now()->toDateString(),
            $journal->type,
            $description ?? 'Pembalikan '.$journal->journal_no,
            $journal->source,
            $journal->journal_no,
        );

        $journal->forceFill(['status' => 'reversed', 'reversed_by' => $reversal->id])->saveQuietly();

        return $reversal;
    }

    /** Reverses every posted journal generated by a document. */
    public function reverseForSource(Model $source, ?string $date = null): int
    {
        $journals = Journal::query()
            ->where('source_type', $source::class)
            ->where('source_id', $source->getKey())
            ->where('status', 'posted')
            ->with('lines')
            ->get();

        foreach ($journals as $journal) {
            $this->reverse($journal, $date);
        }

        return $journals->count();
    }

    private function guardPeriod(string $date): void
    {
        if (FiscalPeriod::isLocked($date)) {
            throw new RuntimeException('Periode akuntansi untuk tanggal '.$date.' sudah ditutup.');
        }
    }
}
