@php
    /**
     * Journals generated by a posted document, shown on its detail page.
     * Hidden when the accounting module is off — the entries are still written,
     * they just are not part of this installation's workflow.
     */
    $journals = $journals ?? collect();
@endphp

@if($journals->isNotEmpty() && app(\App\Services\ModuleRegistry::class)->enabled('accounting'))
    <x-card title="Jurnal Terkait" flush class="mt-3">
        <div class="table-responsive">
            <table class="table table-vcenter card-table">
                <thead>
                <tr>
                    <th>No. Jurnal</th><th>Tanggal</th><th>Keterangan</th>
                    <th class="text-num">Debit</th><th class="text-num">Kredit</th><th>Status</th>
                </tr>
                </thead>
                <tbody>
                @foreach($journals as $journal)
                    <tr>
                        <td><a href="{{ route('journals.show', $journal) }}">{{ $journal->journal_no }}</a></td>
                        <td>{{ fdate($journal->date) }}</td>
                        <td class="text-secondary">{{ $journal->description }}</td>
                        <td class="text-num">{{ rupiah($journal->total_debit) }}</td>
                        <td class="text-num">{{ rupiah($journal->total_credit) }}</td>
                        <td><x-status :value="$journal->status" /></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </x-card>
@endif
